apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
  namespace: sendai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-replica
  template:
    metadata:
      labels:
        app: redis-replica
        role: replica
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          command:
            - redis-server
            - --replicaof
            - redis-primary
            - "6379"
            - --appendonly
            - "yes"
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
